version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: wikijs_postgres
    restart: always
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijs_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: wikijs_elastic
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  wikijs:
    image: requarks/wiki:latest
    container_name: wikijs
    restart: always
    depends_on:
      - postgres
      - elasticsearch
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs_password
      DB_NAME: wiki
      SEARCH_TYPE: elasticsearch
      SEARCH_HOST: http://elasticsearch:9200
    ports:
      - "3000:3000"

  kibana:
      image: docker.elastic.co/kibana/kibana:8.10.2
      container_name: wikijs_kibana
      restart: always
      depends_on:
        - elasticsearch
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      ports:
        - "5601:5601"

volumes:
  pgdata:
  esdata:
